### PR TITLE
fixed typos on readme

### PR DESCRIPTION
**Pull request by naofumi-fujii**
fixed typos :sushi: 
- additiona_ops -> additional_ops
- rspec-kcikstarter -> rspec-kickstarter

### CODE REVIEW

**Comment by seratch** [comment]
@naofumi-fujii Thanks. Why did you close this PR?

**Comment by naofumi-fujii** [comment]
@seratch 
i noticed that this repo was last updated year ago so i thought this will be never merged. :honey_pot: 
on the other hand i couldnt solve how to pass the travis test.

**Comment by seratch** [comment]
>i noticed that this repo was last updated year ago so i thought this will be never merged. 
Surely not.

>couldnt solve how to pass the travis test.
Would you please re-open this PR? I'll check the failure.

**Comment by naofumi-fujii** [comment]
reopened! thanks :+1:

**Comment by seratch** [comment]
I'll fix the failures later. Thanks for your contribution! :+1:

**Comment by naofumi-fujii** [comment]
@seratch thank you! :+1: :+1:

**Comment by seratch** [comment]
Build issue has been fixed.

**Comment by naofumi-fujii** [comment]
thanks :+1:

**Pull request merged**
